#pragma config(Sensor, dgtl1,  quadLeft,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LEDgreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  LEDyellow,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  LEDred,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  progSkills,     sensorTouch)
#pragma config(Sensor, dgtl11, quadRight,      sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftCLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMGLift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           drvBottomLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           drvBottomRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           drvTopRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           drvTopLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightMGLeft,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightCLift,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
